---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: vagrant

platforms:
  - name: ubuntu-14.04
    driver:
      box: express42/ubuntu-14.04
      provider: parallels
  - name: ubuntu-12.04
    driver:
      box: express42/ubuntu12.04-chef11
      provider: parallels

suites:
  - name: base
    run_list:
      - role[base]
    attributes:
  - name: graylog
    run_list:
      - role[base]
      - role[graylog]
  - name: zabbix
    run_list:
      - role[base]
      - role[zabbix]
  - name: ruby
    run_list:
      - role[base]
      - role[ruby]
